### PR TITLE
Manage replicate_ignore_table special case

### PR DESCRIPTION
**Pull request by vide**
### Description of the change

This setting is a special case in mysql config because it can be repeated N times with different values, breaking the generic approach to parameters management this role has. To fix it, we specifically check for this param name (it can be easily extened to more params if needed) and expect its value is an array that we then iterate

### Benefits

The role can now apply a config parameter that was previously impossible to manage

### Possible Drawbacks

None?

### CODE REVIEW

**Comment by vide** [comment]
mmmh don't think that the failed travist build is due to my changeset, looks like an infra conf problem :thinking:

**Comment by dortegau** [comment]
Hi @vide,

I think that the problem was that your PR was pointing to master branch instead of develop. This role was renamed last week and these changes aren't in master yet. That's why the Travis build failed.

Once the PR is pointing to develop it works

Thanks for contributing!

**Comment by jnogol** [comment]
Hi @vide 

Could you please update the Changelog with this change? Thx!

**Comment by vide** [comment]
Sure @jnogol but, should I leave it under `unreleased` or where?

**Comment by jnogol** [comment]
Yep, under `unreleased` and please add a link to this PR as in https://github.com/idealista/mysql_role/blame/master/CHANGELOG.md#L11

Thank you!

**Comment by vide** [comment]
Done, but now it conflicts :/ it was just a 3 lines add :/

**Comment by jnogol** [comment]
Solved!

**Pull request merged**
